// src/pages/NoteDetail.jsx
import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import {
  Box,
  Typography,
  Button,
  CircularProgress,
  Alert,
  Stack,
  Snackbar,
  Paper,
  Divider,
  Chip,
} from "@mui/material";
import {
  PictureAsPdf,
  ContentCopy,
  Edit,
  Share,
  ArrowBack,
  Print,
} from "@mui/icons-material";
import jsPDF from "jspdf";
import { getNoteById } from "../firebase/firestoreHelper";

const noteTypeLabels = {
  intake: "Intake",
  standard: "SOAP Session",
  progress: "Progress",
  crisis: "Crisis / Risk",
  discharge: "Discharge",
};

function getCleanNoteText(text) {
  if (!text) return "";

  return text
    .replace(/\*\*/g, "")
    .replace(/__/g, "")
    .replace(/#{1,6}\s?/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export default function NoteDetail() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [note, setNote] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [copiedClean, setCopiedClean] = useState(false);
  const [shareError, setShareError] = useState("");

  useEffect(() => {
    async function fetchNote() {
      try {
        setLoading(true);
        setError("");

        const foundNote = await getNoteById(id);

        if (foundNote) {
          setNote(foundNote);
        } else {
          setError("Note not found.");
        }
      } catch (err) {
        console.error(err);
        setError("Failed to load note.");
      } finally {
        setLoading(false);
      }
    }

    fetchNote();
  }, [id]);

  const handleCopyClean = async () => {
    try {
      const cleanText = getCleanNoteText(note?.formattedNote || "");
      await navigator.clipboard.writeText(cleanText);
      setCopiedClean(true);
    } catch (err) {
      setShareError("Unable to copy note.");
    }
  };

  const handleExportTXT = () => {
    if (!note) return;

    const cleanText = getCleanNoteText(note.formattedNote || "");

    const blob = new Blob([cleanText], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    link.href = url;
    link.download = `${note.title || "soap-note"}.txt`;

    link.click();

    URL.revokeObjectURL(url);
  };

  const handleExportPDF = () => {
    if (!note) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    let y = 20;

    const addFooter = () => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(
        "Generated by NoteWell AI. Clinician review required before use.",
        pageWidth / 2,
        pageHeight - 10,
        { align: "center" }
      );
      doc.setTextColor(0);
    };

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("NoteWell AI", pageWidth / 2, y, { align: "center" });

    y += 12;

    doc.setFontSize(15);
    doc.text(note.title || "SOAP Note", 20, y);

    y += 9;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    const meta = [];

    if (note.clientName) meta.push(`Client: ${note.clientName}`);
    if (note.sessionDate) meta.push(`Date: ${note.sessionDate}`);
    if (note.sessionLength) meta.push(`Length: ${note.sessionLength} min`);
    if (note.noteType) {
      meta.push(
        `Type: ${noteTypeLabels[note.noteType] || note.noteType || "N/A"}`
      );
    }
    if (note.riskLevel && note.riskLevel !== "none") {
      meta.push(`Risk: ${note.riskLevel}`);
    }

    meta.forEach((line) => {
      doc.text(line, 20, y);
      y += 6;
    });

    y += 5;

    doc.setDrawColor(220);
    doc.line(20, y, pageWidth - 20, y);

    y += 10;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Formatted SOAP Note", 20, y);

    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    const cleanText = getCleanNoteText(note.formattedNote || "");
    const splitText = doc.splitTextToSize(cleanText, pageWidth - 40);

    splitText.forEach((line) => {
      if (y > pageHeight - 22) {
        addFooter();
        doc.addPage();
        y = 20;
      }

      doc.text(line, 20, y);
      y += 5.5;
    });

    addFooter();

    doc.save(`${note.title || "soap-note"}.pdf`);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleShare = async () => {
    if (!note) return;

    const cleanText = getCleanNoteText(note.formattedNote || "");

    if (navigator.share) {
      try {
        await navigator.share({
          title: note.title || "SOAP Note",
          text: cleanText,
        });
      } catch (error) {
        console.error(error);
        setShareError("Sharing was cancelled or failed.");
      }
    } else {
      handleCopyClean();
    }
  };

  if (loading) {
    return (
      <Box sx={{ p: 3 }}>
        <CircularProgress />
      </Box>
    );
  }

  if (error) {
    return (
      <Box sx={{ p: 3 }}>
        <Alert severity="error">{error}</Alert>

        <Button onClick={() => navigate("/my-notes")} sx={{ mt: 2 }}>
          Back to My Notes
        </Button>
      </Box>
    );
  }

  return (
    <Box maxWidth={900} mx="auto" sx={{ p: { xs: 2, sm: 3 } }}>
      <Stack spacing={1} sx={{ mb: 2 }}>
        <Typography variant="h4">
          {note.title || "Untitled Note"}
        </Typography>

        <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
          <Chip
            label={noteTypeLabels[note.noteType] || note.noteType || "N/A"}
            size="small"
          />

          {note.auditSafe && (
            <Chip
              label="Audit-Safe"
              color="success"
              size="small"
              variant="outlined"
            />
          )}

          {note.clientName && (
            <Chip label={`Client: ${note.clientName}`} size="small" />
          )}

          {note.sessionDate && (
            <Chip label={`Date: ${note.sessionDate}`} size="small" />
          )}

          {note.sessionLength && (
            <Chip label={`${note.sessionLength} min`} size="small" />
          )}

          {note.riskLevel && note.riskLevel !== "none" && (
            <Chip label={`Risk: ${note.riskLevel}`} size="small" />
          )}
        </Stack>
      </Stack>

      <Paper
        elevation={0}
        sx={{
          p: 2,
          border: "1px solid #e5e7eb",
          borderRadius: 2,
          mb: 3,
          bgcolor: "#fafafa",
        }}
      >
        <Typography variant="subtitle2" color="text.secondary" sx={{ mb: 1 }}>
          Note Actions
        </Typography>

        <Stack spacing={1.5}>
          <Stack direction={{ xs: "column", sm: "row" }} spacing={1}>
            <Button
              fullWidth
              variant="contained"
              startIcon={<Edit />}
              onClick={() => navigate(`/edit-note/${id}`)}
            >
              Edit Note
            </Button>

            <Button
              fullWidth
              variant="contained"
              startIcon={<PictureAsPdf />}
              onClick={handleExportPDF}
            >
              Download PDF
            </Button>
          </Stack>

          <Stack direction={{ xs: "column", sm: "row" }} spacing={1}>
            <Button
              fullWidth
              variant="outlined"
              startIcon={<ContentCopy />}
              onClick={handleCopyClean}
            >
              Copy
            </Button>

            <Button
              fullWidth
              variant="outlined"
              startIcon={<Print />}
              onClick={handlePrint}
            >
              Print
            </Button>

            <Button
              fullWidth
              variant="outlined"
              startIcon={<Share />}
              onClick={handleShare}
            >
              Share
            </Button>
          </Stack>

          <Stack direction={{ xs: "column", sm: "row" }} spacing={1}>
            <Button fullWidth variant="text" onClick={handleExportTXT}>
              Export TXT
            </Button>

            <Button
              fullWidth
              variant="text"
              startIcon={<ArrowBack />}
              onClick={() => navigate("/my-notes")}
            >
              Back to My Notes
            </Button>
          </Stack>
        </Stack>
      </Paper>

      <Divider sx={{ my: 2 }} />

      <Paper sx={{ p: 2, mb: 2 }} elevation={2}>
        <Typography variant="subtitle2" gutterBottom>
          Raw Note
        </Typography>

        <Typography sx={{ whiteSpace: "pre-wrap" }}>
          {note.rawNote || "No raw note available."}
        </Typography>
      </Paper>

      <Paper sx={{ p: 2, mb: 4 }} elevation={2}>
        <Typography variant="subtitle2" gutterBottom>
          Formatted SOAP Note
        </Typography>

        <Typography sx={{ whiteSpace: "pre-wrap" }}>
          {note.formattedNote || "No formatted note available."}
        </Typography>
      </Paper>

      <Snackbar
        open={copiedClean}
        autoHideDuration={3000}
        onClose={() => setCopiedClean(false)}
        message="Note copied."
      />

      <Snackbar
        open={!!shareError}
        autoHideDuration={3000}
        onClose={() => setShareError("")}
        message={shareError}
      />
    </Box>
  );
}